version: '3.1' #format version for this docker compose file

services:
  mongo-container:
    image: mongo:4.0.4
    container_name: translator_db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"

  app:
    container_name: translator_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - mongo-container

volumes:
  mongo-volume:

